# This is a basic workflow that is manually triggered
            - nombre: Acción APK
  # Puedes anclar al commit exacto o a la versión.
  # usos: WaterLemons2k/apk-action@6872ea1c0a08c2646b5a9cfd7d5262659050c0ff
  usos: WaterLemons2k/apk-action@v1.1.2
  con:
    # Contenido del archivo del almacén de claves (.jks), codificado en base64
    almacén de claves:
    # Contraseña del almacén de claves
    contraseña del almacén de claves:
    # Alias de la clave
    alias de clave:
    # Contraseña de la clave
    clave-contraseña:
    # La versión de Java para configurar
    java-version: # opcional
    # Los argumentos pasados a Gradle
    gradle-args: # opcional, el valor predeterminado es --no-daemon
    # Construir un APK de lanzamiento o depuración
    release: # opcional, el valor predeterminado es verdadero
          
      
          
